<script setup>
import { ref, computed, nextTick, onMounted, onBeforeUnmount } from 'vue'
import FlowIcon from './components/FlowIcon.vue'
import { useWallet } from './composables/useWallet'
import { CLUSTER_LABEL, SOCIAL_URL, TOKEN_EXPLORER_URL, TOKEN_MINT, TOKEN_SYMBOL } from './config'

const { connected, account, shortAccount, balance, tokenBalance, walletCluster, correctNetwork, isConnecting, isRefreshing, walletError, tokenError, tokenNotice, tokenConfigured, connectWallet, disconnect, refreshBalances } = useWallet()
const walletStatusDescription = computed(() => {
  if (!connected.value) return 'Local previews work without a wallet.'
  if (correctNetwork.value === false) return `Wallet reports Solana ${walletCluster.value}; balance reads are paused because this app uses ${CLUSTER_LABEL}. Select ${CLUSTER_LABEL} in the wallet to read its balance. The app will not switch networks.`
  const observedCluster = walletCluster.value === 'unknown' ? 'an unverified wallet cluster' : `Solana ${walletCluster.value}`
  return `Wallet reports ${observedCluster}; native SOL is read from ${CLUSTER_LABEL} RPC.`
})
const pages = ['Overview', 'Pools', 'Positions', 'Governance']
const activePage = ref('Overview')
const search = ref('')
const filter = ref('All pools')
const sort = ref('featured')
const allocation = ref(50)
const pools = [
  { id: 'orl-sol', name: 'ORL / SOL', pair: 'ORL / SOL', token: 'ORL', profile: 'Core', apr: 18.4, tvl: 2.84, volume: 184.2, fee: '0.30%', color: 'green', symbols: ['O', 'S'], model: 'Balanced liquidity' },
  { id: 'sol-usdc', name: 'SOL / USDC', pair: 'SOL / USDC', token: 'SOL', profile: 'Stable', apr: 9.8, tvl: 14.2, volume: 902.6, fee: '0.05%', color: 'purple', symbols: ['S', '$'], model: 'Stable pair liquidity' },
  { id: 'orl-usdc', name: 'ORL / USDC', pair: 'ORL / USDC', token: 'ORL', profile: 'Experimental', apr: 31.6, tvl: 0.92, volume: 74.8, fee: '1.00%', color: 'orange', symbols: ['O', '$'], model: 'Variable liquidity' },
]
const filteredPools = computed(() => {
  const query = search.value.trim().toLowerCase()
  const rows = pools.filter(p => (filter.value === 'All pools' || p.profile === filter.value) && `${p.name} ${p.pair} ${p.profile}`.toLowerCase().includes(query))
  if (sort.value === 'apr') rows.sort((a, b) => b.apr - a.apr)
  if (sort.value === 'tvl') rows.sort((a, b) => b.tvl - a.tvl)
  return rows
})
const selectedPoolId = ref(pools[0].id)
const selectedPool = computed(() => pools.find(p => p.id === selectedPoolId.value) || pools[0])
const secondaryToken = computed(() => selectedPool.value.pair.split(' / ')[1])
const allocationLabel = computed(() => `${allocation.value}% ${selectedPool.value.token}, ${100 - allocation.value}% ${secondaryToken.value}`)
const positions = ref([])
const storageKey = 'solana.preview-positions.v1'
const modal = ref('')
const previewStep = ref(1)
const previewAmount = ref('')
const reviewedAmount = ref('')
const amountError = ref('')
const acknowledged = ref(false)
const dialog = ref(null)
const previewInput = ref(null)
const toast = ref('')
let previousFocus = null
let toastTimer

function notify(message) { clearTimeout(toastTimer); toast.value = message; toastTimer = setTimeout(() => { toast.value = '' }, 4200) }
function readRoute() {
  const hash = window.location.hash.slice(1).toLowerCase()
  activePage.value = hash === 'staking' ? 'Positions' : pages.find(p => p.toLowerCase() === hash) || 'Overview'
  document.title = `${activePage.value} | VelaCircuit`
}
function goTo(page) { closeModal(); activePage.value = page; window.location.hash = page.toLowerCase(); window.scrollTo({ top: 0, behavior: 'instant' }); nextTick(() => document.getElementById('main-content')?.focus({ preventScroll: true })) }
function openModal(type) { if (modal.value) return; previousFocus = document.activeElement; modal.value = type; document.body.style.overflow = 'hidden'; nextTick(() => { dialog.value?.showModal(); if (type === 'pool') previewInput.value?.focus() }) }
function closeModal() { if (dialog.value?.open) dialog.value.close(); else modal.value = '' }
function onDialogClose() { document.body.style.overflow = ''; modal.value = ''; if (previousFocus?.isConnected) previousFocus.focus({ preventScroll: true }) }
function onBackdrop(event) { if (event.target !== dialog.value) return; const r = dialog.value.getBoundingClientRect(); if (event.clientX < r.left || event.clientX > r.right || event.clientY < r.top || event.clientY > r.bottom) closeModal() }
function openPool(pool) { selectedPoolId.value = pool.id; previewStep.value = 1; previewAmount.value = ''; reviewedAmount.value = ''; amountError.value = ''; acknowledged.value = false; openModal('pool') }
function validAmount(value) { return typeof value === 'string' && /^(?:\d+(?:\.\d{1,6})?|\.\d{1,6})$/.test(value.trim()) && Number(value) > 0 && Number(value) <= 1000000 }
function reviewPreview() { if (!validAmount(previewAmount.value)) { amountError.value = 'Enter an amount above 0 with up to 6 decimal places.'; previewInput.value?.focus(); return }; amountError.value = ''; reviewedAmount.value = String(Number(previewAmount.value)); previewStep.value = 2 }
function loadPositions() { try { const saved = JSON.parse(sessionStorage.getItem(storageKey) || '[]'); if (Array.isArray(saved)) positions.value = saved.filter(p => p && pools.some(pool => pool.id === p.poolId) && validAmount(p.amount)).slice(0, 100) } catch { positions.value = [] } }
function savePreview() { if (!acknowledged.value || !validAmount(reviewedAmount.value)) return; positions.value.unshift({ id: crypto.randomUUID?.() || `preview-${Date.now()}`, poolId: selectedPool.value.id, amount: reviewedAmount.value, createdAt: Date.now() }); sessionStorage.setItem(storageKey, JSON.stringify(positions.value)); goTo('Positions'); notify('Preview saved locally. No assets moved and no transaction was sent.') }
function removePosition(position) { positions.value = positions.value.filter(p => p.id !== position.id); sessionStorage.setItem(storageKey, JSON.stringify(positions.value)); notify('Preview removed from this session.') }
function poolFor(position) { return pools.find(p => p.id === position.poolId) || pools[0] }
function displayDate(value) { return new Date(value).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) }
function displayAmount(value) { return Number(value).toLocaleString('en-US', { maximumFractionDigits: 6 }) }
function resetFilters() { filter.value = 'All pools'; search.value = ''; sort.value = 'featured' }
async function connect() { const ok = await connectWallet(); if (ok) notify('Solana wallet connected.') }
async function copyAddress() { if (!account.value) return; await navigator.clipboard?.writeText(account.value); notify('Wallet address copied.') }
onMounted(() => { readRoute(); loadPositions(); window.addEventListener('hashchange', readRoute) })
onBeforeUnmount(() => { window.removeEventListener('hashchange', readRoute); clearTimeout(toastTimer) })
</script>

<template>
  <div class="app-shell">
    <a class="skip-link" href="#main-content" @click.prevent="document.getElementById('main-content')?.focus()">Skip to content</a>
    <header class="app-header">
      <div class="header-inner">
        <a class="wordmark" href="#overview" @click.prevent="goTo('Overview')" aria-label="VelaCircuit home"><img src="/velacircuit-mark.svg" alt="" width="34" height="34"><span>velacircuit<span class="wordmark-dot">.</span></span></a>
        <nav class="main-nav" aria-label="Main navigation">
          <a v-for="page in pages" :key="page" :href="'#' + page.toLowerCase()" :class="{ active: activePage === page }" :aria-current="activePage === page ? 'page' : undefined" @click.prevent="goTo(page)"><FlowIcon :name="{ Overview: 'grid', Pools: 'layers', Positions: 'portfolio', Governance: 'community' }[page]" /><span>{{ page }}</span><b v-if="page === 'Positions' && positions.length" class="nav-count">{{ positions.length }}</b></a>
        </nav>
        <div class="header-actions"><span class="network-badge"><i class="status-dot"></i>{{ CLUSTER_LABEL }}</span><button class="button button-wallet" @click="openModal('wallet')"><FlowIcon name="wallet" />{{ connected ? shortAccount : 'Connect wallet' }}</button></div>
      </div>
    </header>

    <main id="main-content" tabindex="-1" class="workspace">
      <section v-if="activePage === 'Overview'" class="overview-page">
        <div class="market-strip"><span><i class="status-dot"></i> {{ CLUSTER_LABEL.toUpperCase() }} DESK</span><span class="strip-disclosure">Fictional UI fixtures - no live market feed</span><button class="text-button" @click="openModal('docs')">Read the guide <FlowIcon name="arrow" /></button></div>
        <div class="overview-grid">
          <section class="hero-card">
            <div class="hero-copy"><span class="hero-label"><i class="status-dot"></i> NON-CUSTODIAL PRACTICE MODE</span><h1 id="hero-title">Trade the<br><em>idea.</em></h1><p>Compare simulated Solana pool routes, tune an illustrative split, and save session-only practice positions.</p><button class="button button-dark" @click="goTo('Pools')">Browse pools <FlowIcon name="arrow" /></button></div>
            <div class="coin-scene" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="hero-coin coin-sol"><span>S</span></div><div class="hero-coin coin-token"><span>O</span></div><div class="hero-coin coin-dollar"><span>$</span></div><span class="scene-label">SOLANA / 2026</span></div>
            <div class="hero-bottom"><span><FlowIcon name="shield" /> No deposit required</span><span>SIMULATION ONLY</span></div>
          </section>
          <section class="model-launcher" aria-label="Pool preview builder">
            <div class="panel-heading"><div><span class="eyebrow">SYNTHETIC FIXTURES</span><h2>Build a position</h2></div><span class="tag tag-green">PRACTICE</span></div>
            <div class="model-options" role="group" aria-label="Pool model"><button v-for="(pool, index) in pools" :key="pool.id" class="model-option" :class="{ selected: selectedPool.id === pool.id }" :aria-pressed="selectedPool.id === pool.id" @click="selectedPoolId = pool.id; allocation = [50, 70, 35][index]"><span :class="['model-token', pool.color]">{{ pool.symbols[0] }}</span><span><strong>{{ pool.name }}</strong><small>{{ pool.pair }}</small></span><span class="selection-dot"><FlowIcon v-if="selectedPool.id === pool.id" name="check" /></span></button></div>
            <div class="mix-box"><div class="mix-caption"><span>Allocation split</span><span>Illustrative only</span></div><div class="mix-content"><div class="mix-ring" :style="{ '--mix': allocation + '%' }" role="img" :aria-label="allocationLabel"><span>{{ allocation }}%</span></div><div class="allocation-controls"><div class="allocation-labels"><label for="allocation-range"><i class="legend-dot green"></i>{{ selectedPool.token }}<strong>{{ allocation }}%</strong></label><span><i class="legend-dot violet"></i>{{ secondaryToken }}<strong>{{ 100 - allocation }}%</strong></span></div><input id="allocation-range" v-model.number="allocation" type="range" min="10" max="90" step="5" :aria-valuetext="allocationLabel"><div class="range-caption"><span>Drag to rebalance</span><button class="text-button" @click="allocation = 50">Reset</button></div></div></div></div>
            <div class="model-sample"><div><span>Demo APR</span><strong>{{ selectedPool.apr }}<small>%</small></strong></div><div><span>Demo TVL</span><strong><small>$</small>{{ selectedPool.tvl }}<small>M</small></strong></div><div><span>Demo volume</span><strong><small>$</small>{{ selectedPool.volume }}<small>M</small></strong></div></div>
            <button class="button button-primary full-width launch-button" @click="openPool(selectedPool)">Preview position <FlowIcon name="arrow" /></button><p class="launch-caption">No wallet signature. No real returns.</p>
          </section>
        </div>
        <section class="featured-section"><div class="section-label"><div><span class="eyebrow">MARKET BOARD</span><h2>Pool routes<span class="heading-dot">.</span></h2><p>Fictional demo metrics only; none of these pools or fee routes are live.</p></div><button class="text-button" @click="goTo('Pools')">Open pool board <FlowIcon name="arrow" /></button></div><div class="featured-table"><div class="featured-head"><span>POOL / PAIR</span><span>DEMO APR</span><span>DEMO TVL</span><span>DEMO VOLUME</span><span>FEE</span></div><button v-for="pool in pools" :key="pool.id" class="featured-row" @click="openPool(pool)"><span class="featured-identity"><span :class="['token-pair', pool.color]"><span>{{ pool.symbols[0] }}</span><span>{{ pool.symbols[1] }}</span></span><span><strong>{{ pool.name }}</strong><small>{{ pool.pair }}</small></span></span><span class="featured-apy">{{ pool.apr }}<small>%</small></span><span>${{ pool.tvl }}M</span><span>${{ pool.volume }}M</span><span class="tag">{{ pool.fee }}</span></button></div></section>
        <section class="wallet-banner"><div class="banner-icon"><FlowIcon name="wallet" /></div><div><h3>Read your SOL and ORL.</h3><p>Read native SOL and ORL balances from {{ CLUSTER_LABEL }}. Pool, swap, and governance actions remain unavailable until their programs are deployed.</p></div><button class="button button-secondary" @click="openModal('wallet')">{{ connected ? 'Manage wallet' : 'Connect wallet' }} <FlowIcon name="arrow" /></button></section>
      </section>

      <section v-if="activePage === 'Pools'" class="discovery-page"><div class="page-heading"><div><span class="eyebrow"><span class="tiny-rule"></span> POOL BOARD</span><h1>Choose a route.</h1><p>Compare fictional demo routes and save a local practice position.</p></div><span class="tag tag-purple">NOT MARKET DATA</span></div><div class="filter-bar"><div class="filter-tabs"><button v-for="option in ['All pools', 'Core', 'Stable', 'Experimental']" :key="option" :class="{ selected: filter === option }" @click="filter = option">{{ option }}</button></div><label class="search-field"><FlowIcon name="search" /><input v-model="search" type="search" placeholder="Search pools" aria-label="Search pools"></label><select v-model="sort" aria-label="Sort pools"><option value="featured">Featured</option><option value="apr">Demo APR</option><option value="tvl">Demo TVL</option></select></div><div class="pool-grid"><article v-for="pool in filteredPools" :key="pool.id" :class="['pool-card', pool.color]"><div class="pool-card-head"><span class="token-pair"><span>{{ pool.symbols[0] }}</span><span>{{ pool.symbols[1] }}</span></span><span class="tag">{{ pool.profile }}</span></div><h2>{{ pool.name }}</h2><p>{{ pool.model }} / {{ pool.fee }} fee</p><div class="mini-chart"><i v-for="n in 16" :key="n" :style="{ height: (25 + ((n * 17 + pool.apr * 3) % 65)) + '%' }"></i></div><div class="pool-metrics"><div><span>Demo APR</span><strong>{{ pool.apr }}%</strong></div><div><span>Demo TVL</span><strong>${{ pool.tvl }}M</strong></div><div><span>Demo 24h</span><strong>${{ pool.volume }}M</strong></div></div><button class="button button-secondary full-width" @click="openPool(pool)">Preview route <FlowIcon name="arrow" /></button><small class="pool-card-footnote">Fictional figures / not market data</small></article></div><div v-if="!filteredPools.length" class="empty-state"><FlowIcon name="search" /><h2>No routes found</h2><p>Try another token or reset the filters.</p><button class="button button-secondary" @click="resetFilters">Reset filters</button></div></section>

      <section v-if="activePage === 'Positions'" class="positions-page"><div class="page-heading"><div><span class="eyebrow"><span class="tiny-rule"></span> LOCAL LEDGER</span><h1>Your positions.</h1><p>Saved in this browser tab. They never touch the chain.</p></div><button class="button button-primary" @click="goTo('Pools')"><FlowIcon name="plus" /> New preview</button></div><div class="position-summary"><span class="stat-icon purple"><FlowIcon name="portfolio" /></span><div><span>Saved previews</span><strong>{{ String(positions.length).padStart(2, '0') }}</strong></div><span class="tag">SESSION ONLY</span></div><div v-if="!positions.length" class="empty-state position-empty"><span class="empty-icon"><FlowIcon name="layers" /></span><h2>Your first route is waiting.</h2><p>Choose a pool, add a practice amount, and review the split.</p><button class="button button-primary" @click="goTo('Pools')">Open pool board <FlowIcon name="arrow" /></button></div><div v-else class="positions-ledger"><div class="ledger-head"><span>ROUTE / CREATED</span><span>AMOUNT</span><span>STATUS</span><span>ACTIONS</span></div><article v-for="position in positions" :key="position.id" class="position-entry"><div class="entry-identity"><span :class="['entry-icon', poolFor(position).color]">{{ poolFor(position).symbols[0] }}</span><div><h2>{{ poolFor(position).name }}</h2><p>{{ poolFor(position).profile }} / {{ displayDate(position.createdAt) }}</p></div></div><div class="position-amount">{{ displayAmount(position.amount) }}<span>{{ poolFor(position).token }}</span></div><span class="position-status"><i class="status-dot"></i> Preview</span><button class="square-button remove-button" :aria-label="'Remove ' + poolFor(position).name + ' preview'" @click="removePosition(position)"><FlowIcon name="trash" /></button></article></div><p class="session-note"><FlowIcon name="shield" /> Simulation only: no deposits, fees, or accrued returns.</p></section>

      <section v-if="activePage === 'Governance'" class="governance-page"><div class="page-heading"><div><span class="eyebrow"><span class="tiny-rule"></span> PROTOCOL STATUS</span><h1>Ship the rails first.</h1><p>VelaCircuit keeps the first release focused on research and local practice.</p></div><span class="tag tag-purple">COMING LATER</span></div><div class="governance-layout"><section class="governance-status-panel"><div class="governance-glyph"><FlowIcon name="community" /></div><span class="eyebrow">TOKEN + PROGRAM</span><h2>{{ tokenConfigured ? 'ORL mint live.' : 'Mint pending.' }}<br>Governance paused.</h2><p>{{ tokenConfigured ? 'The ORL classic SPL Token mint is deployed on Solana Testnet. Pool and voting programs are not deployed.' : 'No Solana token mint, pool program, or voting account is deployed in this workspace.' }}</p><div class="governance-status"><i class="status-dot"></i> {{ tokenConfigured ? 'ORL mint live; zero initial supply' : 'Waiting for deployment inputs' }}</div><p v-if="tokenConfigured" class="muted-note"><a :href="TOKEN_EXPLORER_URL" target="_blank" rel="noopener noreferrer">View ORL mint on Solana Explorer <FlowIcon name="arrow" /></a></p><p v-else class="muted-note">A future mint address and program ID will be configured here.</p></section><section class="roadmap-panel"><div class="panel-heading"><div><span class="eyebrow">CAPABILITY MAP</span><h2>What works today.</h2></div></div><ol class="roadmap-list"><li><span class="roadmap-node"><FlowIcon name="check" /></span><div><span class="tag tag-green">AVAILABLE</span><h3>Compare and simulate</h3><p>Browse fictional pool fixtures and save local previews without a wallet.</p><button class="text-button" @click="goTo('Pools')">Open pool board <FlowIcon name="arrow" /></button></div></li><li><span class="roadmap-node"><FlowIcon name="check" /></span><div><span class="tag tag-blue">OPTIONAL</span><h3>Read a Solana wallet</h3><p>Connect an injected wallet to read native SOL and ORL balances from the configured RPC.</p><button class="text-button" @click="openModal('wallet')">Manage wallet <FlowIcon name="arrow" /></button></div></li><li class="future-step"><span class="roadmap-node"><FlowIcon name="clock" /></span><div><span class="tag">WAITING</span><h3>Pools, swaps, governance</h3><p>These actions stay disabled until their programs and governance accounts are deployed.</p></div></li></ol></section></div></section>
    </main>

    <footer class="site-footer"><div><span class="footer-brand">velacircuit</span><span>Trade the tide.</span></div><div class="footer-links"><button @click="openModal('docs')">Guide <FlowIcon name="external" /></button><a v-if="SOCIAL_URL" :href="SOCIAL_URL" target="_blank" rel="noopener noreferrer">Follow on X <FlowIcon name="external" /></a><span>(c) 2026</span></div><p>The ORL mint is live on Testnet. Pool routes and positions are simulations; no pool program is deployed.</p></footer>

    <dialog ref="dialog" class="app-dialog" :class="{ 'guide-dialog': modal === 'docs' }" aria-labelledby="dialog-title" @click="onBackdrop" @close="onDialogClose">
      <div class="dialog-inner"><button class="dialog-close square-button" aria-label="Close dialog" @click="closeModal"><FlowIcon name="close" /></button>
        <template v-if="modal === 'pool'"><div class="dialog-kicker"><span class="dialog-icon"><FlowIcon name="layers" /></span><span>LOCAL PREVIEW</span><span class="dialog-step">{{ previewStep }} / 2</span></div><h2 id="dialog-title">{{ previewStep === 1 ? selectedPool.name : 'Review route' }}</h2><p class="dialog-lead">{{ selectedPool.pair }} / {{ selectedPool.model }}</p><div class="dialog-notice"><FlowIcon name="shield" /><p>No assets move and no transaction is sent. The pool route, APR, TVL, and volume are fictional interface fixtures, not market data.</p></div><form v-if="previewStep === 1" @submit.prevent="reviewPreview"><label class="field-label" for="preview-amount">Practice amount</label><div class="amount-input"><input id="preview-amount" ref="previewInput" v-model="previewAmount" inputmode="decimal" placeholder="0.00" :aria-invalid="Boolean(amountError)"><span>{{ selectedPool.token }}</span></div><p v-if="amountError" class="form-error" role="alert">{{ amountError }}</p><div class="quick-amounts"><button v-for="amount in ['100', '500', '1000']" :key="amount" type="button" @click="previewAmount = amount">{{ amount }} {{ selectedPool.token }}</button></div><div class="review-lines"><div><span>Demo APR</span><b>{{ selectedPool.apr }}% / fictional</b></div><div><span>Network transaction</span><b>None</b></div></div><button class="button button-primary full-width" type="submit">Review preview <FlowIcon name="arrow" /></button></form><template v-else><div class="review-amount"><span>PRACTICE AMOUNT</span><strong>{{ displayAmount(reviewedAmount) }} <small>{{ selectedPool.token }}</small></strong></div><div class="review-lines"><div><span>Route</span><b>{{ selectedPool.name }}</b></div><div><span>Allocation</span><b>{{ allocationLabel }}</b></div><div><span>Saved to</span><b>This tab only</b></div></div><label class="check-label"><input v-model="acknowledged" type="checkbox"><span>I understand this is a simulation.</span></label><button class="button button-primary full-width" :disabled="!acknowledged" @click="savePreview">Save local preview <FlowIcon name="check" /></button><button class="text-button back-button" @click="previewStep = 1">Back to amount</button></template></template>
        <template v-else-if="modal === 'wallet'"><div class="dialog-kicker"><span class="dialog-icon"><FlowIcon name="wallet" /></span><span>SOLANA WALLET</span></div><h2 id="dialog-title">Your wallet, when ready.</h2><p class="dialog-lead">Connect Phantom or another Solana wallet to read native SOL and ORL balances from the configured {{ CLUSTER_LABEL }} RPC. The wallet's selected cluster is not switched.</p><div class="wallet-status-card"><FlowIcon name="wallet" /><div><strong>{{ connected ? shortAccount : 'No wallet connected' }}</strong><span>{{ walletStatusDescription }}</span></div><i v-if="connected" class="status-dot"></i></div><template v-if="connected"><button class="wallet-address" @click="copyAddress">{{ account }}</button><div class="review-lines"><div><span>Native balance</span><b>{{ balance ?? '—' }} SOL</b></div><div><span>{{ TOKEN_SYMBOL }} balance</span><b>{{ tokenConfigured ? (tokenBalance ?? '—') : 'Mint pending' }}</b></div></div><button class="button button-secondary full-width" :disabled="isRefreshing" @click="refreshBalances">{{ isRefreshing ? 'Refreshing...' : 'Refresh balance' }} <FlowIcon name="refresh" /></button><button class="text-button full-width" @click="disconnect">Disconnect wallet</button></template><button v-else class="button button-primary full-width" :disabled="isConnecting" @click="connect">{{ isConnecting ? 'Waiting for wallet...' : 'Connect Solana wallet' }} <FlowIcon name="wallet" /></button><p v-if="walletError" class="form-error" role="alert">{{ walletError }}</p><p v-if="tokenError" class="form-error" role="alert">{{ tokenError }}</p><p v-if="tokenNotice" class="token-notice">{{ tokenNotice }}</p><div :class="['mint-pending', { 'is-live': tokenConfigured }]"><span class="eyebrow">TOKEN STATUS</span><strong>{{ tokenConfigured ? TOKEN_SYMBOL + ' live on ' + CLUSTER_LABEL : 'Mint pending' }}</strong><p>{{ tokenConfigured ? 'Classic SPL Token; 9 decimals; zero initial supply. Mint authority retained; freeze authority disabled. Pool and faucet actions are not deployed.' : 'No token mint or faucet has been deployed yet.' }}</p><a v-if="tokenConfigured" class="mint-explorer" :href="TOKEN_EXPLORER_URL" target="_blank" rel="noopener noreferrer">View mint on Explorer <FlowIcon name="arrow" /></a><code v-if="tokenConfigured" class="mint-address">{{ TOKEN_MINT }}</code></div></template>
        <template v-else-if="modal === 'docs'"><div class="dialog-kicker"><span class="dialog-icon"><FlowIcon name="book" /></span><span>VELACIRCUIT / QUICK START</span></div><h2 id="dialog-title">From pool board to preview.</h2><p class="dialog-lead">A Solana research desk with the ORL mint live on Testnet; pool and governance programs remain pending.</p><div class="guide-step"><span>01</span><div><h3>Compare demo routes</h3><p>Explore fictional pool fixtures. APR, TVL, volume, and fee examples are not market data.</p></div></div><div class="guide-step"><span>02</span><div><h3>Save a local preview</h3><p>Enter an amount, review the allocation, and store it in this browser tab.</p></div></div><div class="guide-step"><span>03</span><div><h3>Connect only for balance reads</h3><p>Wallet connection reads native SOL and ORL from the configured {{ CLUSTER_LABEL }} RPC. It does not switch the wallet's selected cluster or request signatures.</p></div></div><div class="mint-pending is-live"><span class="eyebrow">DEPLOYMENT STATUS</span><strong>ORL mint live on Solana Testnet</strong><p>Zero initial supply; mint authority is retained. Pool program and faucet are not deployed.</p><a class="mint-explorer" :href="TOKEN_EXPLORER_URL" target="_blank" rel="noopener noreferrer">View ORL mint on Explorer <FlowIcon name="arrow" /></a></div><button class="button button-primary full-width" @click="goTo('Pools')">Open pool board <FlowIcon name="arrow" /></button></template>
      </div>
    </dialog>
    <div v-if="toast" class="toast" role="status"><FlowIcon name="check" /><span>{{ toast }}</span><button class="square-button" aria-label="Dismiss notification" @click="toast = ''"><FlowIcon name="close" /></button></div>
  </div>
</template>
